### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by lyuma** [celyk/GPUTrail#1]
Would it be possible to add a license file (usually LICENSE.txt  or COPYING or similar) to the repository, so the licensing of your shader is more clear?

While this is not entirely necessary since you did also submit the shader code to [Godot Shaders](https://godotshaders.com/shader/particle-based-trail/), it would make me feel more comfortable building on top of the trail particles without any licensing confusion.

Thanks!

**Comment by celyk** [comment]
My apologies! I had meant to put the MIT license as usual, but I guess I got distracted by other projects. Done. Is that better now? You should not use the godotshaders version when this one exists.

I'd be delighted for you to contribute to the project! It needs some love, so let me know if you want help understanding the code, or what the plan is and you can pick up where I left off!

**Comment by lyuma** [comment]
Thanks! It's working well for now. Yeah if anything comes up as we use it more I'll let you know.
